import { jsPDF } from 'jspdf';
import type { Client, Product } from '../types';

interface InvoiceItem {
  product: Product;
  quantity: number;
  unitPrice: number;
}

export function generateInvoice(client: Client, items: InvoiceItem[]): void {
  const doc = new jsPDF();
  const date = new Date().toISOString().slice(0, 10);
  const refNo = `INV-${Date.now().toString(36).toUpperCase()}`;

  // Header
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.text('Chemical Replenishment Quote', 14, 22);

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text(`Date: ${date}`, 14, 32);
  doc.text(`Ref: ${refNo}`, 14, 38);

  // Client details
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text('Client', 14, 52);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.text(`${client.name}`, 14, 59);
  doc.text(`Contact: ${client.contact}`, 14, 65);
  doc.text(`Phone: ${client.phone}`, 14, 71);
  doc.text(`System: ${client.systemType}`, 14, 77);

  // Table header
  const tableTop = 90;
  doc.setFillColor(14, 165, 233);
  doc.rect(14, tableTop - 6, 182, 8, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(9);
  doc.text('Product', 16, tableTop);
  doc.text('Qty', 100, tableTop);
  doc.text('Unit', 120, tableTop);
  doc.text('Rate', 140, tableTop);
  doc.text('Total', 168, tableTop);

  // Table rows
  doc.setTextColor(0, 0, 0);
  doc.setFont('helvetica', 'normal');
  let y = tableTop + 10;
  let subtotal = 0;

  for (const item of items) {
    const total = item.quantity * item.unitPrice;
    subtotal += total;
    doc.text(item.product.name, 16, y);
    doc.text(String(item.quantity), 100, y);
    doc.text(item.product.unit, 120, y);
    doc.text(`$${item.unitPrice.toFixed(2)}`, 140, y);
    doc.text(`$${total.toFixed(2)}`, 168, y);
    y += 8;
  }

  // Subtotal
  y += 6;
  doc.setDrawColor(200, 200, 200);
  doc.line(14, y - 4, 196, y - 4);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.text('Subtotal:', 140, y);
  doc.text(`$${subtotal.toFixed(2)}`, 168, y);

  // Footer
  y += 20;
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100, 100, 100);
  doc.text('This quote is valid for 30 days. Prices are subject to change.', 14, y);
  doc.text('Generated by AquaTrack CRM', 14, y + 6);

  doc.save(`Quote_${client.name.replace(/\s+/g, '_')}_${date}.pdf`);
}
